export interface LevelGoal {
    type: string;
    count: number;
}

export interface LevelConfig {
    id: number;
    name: string;
    rows: number;
    cols: number;
    moves: number;
    elements: string[];
    difficult: string;
    goals: LevelGoal[];
    grid: (null | {
        type: string;
        strength?: number;
        content?: { type: string };
    })[][];
    isCompleted: boolean;
}

export const levelConfigs: LevelConfig[] = [
    {
        id: 1,
        name: "Уровень 1",
        rows: 7,
        cols: 6,
        moves: 12,
        difficult: "easy",
        elements: ["phone", "energy", "message", "sim"],
        goals: [
            { type: "sim", count: 15 },
            { type: "phone", count: 15 },
            { type: "box_full", count: 16 },
        ],
        grid: [
            [
                { type: "box", strength: 2 },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "sim" },
                { type: "message" },
                { type: "phone" },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "sim" },

                { type: "phone" },
                {
                    type: "verticallHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "sim" },
                { type: "phone" },
                { type: "message" },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "sim" },
                { type: "phone" },
                { type: "sim" },
                { type: "message" },
                { type: "phone" },
                { type: "sim" },
            ],
            [
                { type: "phone" },
                { type: "message" },
                { type: "phone" },
                { type: "phone" },
                { type: "sim" },
                { type: "message" },
            ],
        ],
        isCompleted: false,
    },

    {
        id: 2,
        name: "Уровень 2",
        rows: 6,
        cols: 6,
        moves: 13,
        difficult: "medium",
        elements: ["smartphone", "energy", "message", "sim"],
        goals: [
            { type: "sim", count: 10 },
            { type: "energy", count: 10 },
        ],
        grid: [
            [
                { type: "energy" },
                { type: "smartphone" },
                { type: "message" },
                { type: "sim" },
                { type: "smartphone" },
                { type: "energy" },
            ],
            [
                { type: "smartphone" },
                { type: "message" },
                { type: "message" },
                { type: "energy" },
                { type: "message" },
                { type: "smartphone" },
            ],
            [
                { type: "smartphone" },
                { type: "energy" },
                { type: "energy" },
                { type: "sim" },
                { type: "energy" },
                { type: "energy" },
            ],
            [
                { type: "sim" },
                { type: "sim" },
                { type: "energy" },
                { type: "sim" },
                { type: "sim" },
                { type: "smartphone" },
            ],
            [
                { type: "message" },
                { type: "sim" },
                { type: "sim" },
                { type: "smartphone" },
                { type: "message" },
                { type: "energy" },
            ],
            [
                { type: "smartphone" },
                { type: "message" },
                { type: "message" },
                { type: "smartphone" },
                { type: "smartphone" },
                { type: "message" },
            ],
        ],
        isCompleted: false,
    },

    {
        id: 3,
        name: "Уровень 3",
        rows: 7,
        cols: 7,
        moves: 12,
        difficult: "easy",
        elements: ["smartphone", "energy", "message", "sim"],
        goals: [
            { type: "smartphone", count: 20 },
            { type: "sim", count: 20 },
        ],
        grid: [
            [
                null,
                { type: "smartphone" },
                { type: "energy" },
                { type: "message" },
                { type: "energy" },
                { type: "energy" },
                null,
            ],
            [
                { type: "smartphone" },
                { type: "energy" },
                { type: "sim" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "message" },
                { type: "sim" },
            ],
            [
                { type: "sim" },
                { type: "energy" },
                { type: "energy" },
                { type: "sim" },
                { type: "smartphone" },
                { type: "energy" },
                { type: "message" },
            ],
            [
                { type: "smartphone" },
                { type: "sim" },
                { type: "smartphone" },
                null,
                { type: "sim" },
                { type: "message" },
                { type: "sim" },
            ],
            [
                { type: "energy" },
                { type: "sim" },
                { type: "smartphone" },
                { type: "smartphone" },
                { type: "message" },
                { type: "sim" },
                { type: "smartphone" },
            ],
            [
                { type: "sim" },
                { type: "smartphone" },
                { type: "sim" },
                { type: "energy" },
                { type: "sim" },
                { type: "smartphone" },
                { type: "message" },
            ],
            [
                null,
                { type: "sim" },
                { type: "sim" },
                { type: "smartphone" },
                { type: "message" },
                { type: "smartphone" },
                null,
            ],
        ],
        isCompleted: false,
    },

    {
        id: 4,
        name: "Уровень 4",
        rows: 5,
        cols: 5,
        isCompleted: false,
        moves: 12,
        difficult: "medium",
        elements: ["smartphone", "energy", "sim", "message"],
        goals: [
            { type: "energy", count: 15 },
            { type: "smartphone", count: 15 },
        ],
        grid: [
            [
                { type: "sim" },
                { type: "message" },
                { type: "sim" },
                { type: "message" },
                { type: "sim" },
            ],
            [
                { type: "energy" },
                { type: "smartphone" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "energy" },
            ],
            [
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "energy" },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "energy" },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
            ],
            [
                { type: "energy" },
                { type: "smartphone" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "energy" },
            ],
            [
                null,
                { type: "energy" },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "energy" },
                null,
            ],
        ],
    },

    {
        id: 5,
        name: "Уровень 5",
        rows: 7,
        cols: 6,
        moves: 15,
        difficult: "easy",
        elements: ["smartphone", "energy", "phone", "message"],
        goals: [
            { type: "energy", count: 10 },
            { type: "smartphone", count: 10 },
            { type: "box_full", count: 8 },
        ],
        grid: [
            [null, null, { type: "message" }, { type: "random" }, null, null],
            [
                null,
                { type: "box", strength: 2 },
                { type: "message" },
                { type: "random" },
                { type: "box", strength: 2 },
                null,
            ],
            [
                { type: "energy" },
                { type: "message" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "phone" },
                { type: "smartphone" },
            ],
            [
                null,
                { type: "random" },
                { type: "energy" },
                { type: "random" },
                { type: "phone" },
                null,
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "message" },
                { type: "energy" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                null,
                { type: "random" },
                { type: "energy" },
                { type: "random" },
                { type: "random" },
                null,
            ],
            [
                null,
                null,
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                null,
                null,
            ],
        ],
        isCompleted: false,
    },

    {
        id: 6,
        name: "Уровень 6",
        rows: 7,
        cols: 6,
        moves: 20,
        difficult: "easy",
        elements: ["smartphone", "energy", "phone", "sim"],
        goals: [
            { type: "energy", count: 20 },
            { type: "smartphone", count: 20 },
        ],
        grid: [
            [
                { type: "phone" },
                { type: "energy" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "energy" },
                { type: "energy" },
            ],
            [
                null,
                { type: "phone" },
                { type: "smartphone" },
                { type: "phone" },
                { type: "phone" },
                null,
            ],
            [
                { type: "phone" },
                { type: "sim" },
                { type: "phone" },
                { type: "sim" },
                { type: "sim" },
                { type: "phone" },
            ],
            [
                { type: "sim" },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                {
                    type: "ice",
                    content: {
                        type: "verticalHelper",
                        isHelper: true,
                        helperType: "verticalHelper",
                    },
                    strength: 2,
                },
                {
                    type: "ice",
                    content: {
                        type: "verticalHelper",
                        isHelper: true,
                        helperType: "verticalHelper",
                    },
                    strength: 2,
                },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "sim" },
            ],
            [
                { type: "sim" },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "sim" },
            ],
            [
                null,
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                null,
            ],
            [
                null,
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                null,
            ],
        ],
        isCompleted: false,
    },

    {
        id: 7,
        name: "Уровень 13",
        rows: 5,
        cols: 5,
        isCompleted: false,
        moves: 10,
        difficult: "easy",
        elements: ["smartphone", "energy", "sim", "phone"],
        goals: [{ type: "smartphone", count: 20 }],
        grid: [
            [
                { type: "smartphone" },
                { type: "smartphone" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "smartphone" },
            ],
            [
                { type: "smartphone" },
                {
                    type: "verticallHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "smartphone" },
            ],
            [
                { type: "phone" },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                {
                    type: "discoball",
                    isHelper: true,
                    helperType: "discoball",
                },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "phone" },
            ],
            [
                { type: "smartphone" },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                {
                    type: "verticallHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                { type: "smartphone" },
            ],
            [
                { type: "smartphone" },
                { type: "smartphone" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "smartphone" },
            ],
        ],
    },

    {
        id: 8,
        name: "Уровень 8",
        rows: 6,
        cols: 5,
        isCompleted: false,
        moves: 15,
        difficult: "medium",
        elements: ["smartphone", "energy", "sim", "phone"],
        goals: [
            { type: "energy", count: 15 },
            { type: "sim", count: 15 },
        ],
        grid: [
            [
                { type: "energy" },
                { type: "sim" },
                { type: "energy" },
                { type: "energy" },
                { type: "sim" },
            ],
            [
                { type: "energy" },
                { type: "phone" },
                { type: "energy" },
                { type: "sim" },
                { type: "sim" },
            ],
            [
                { type: "sim" },
                { type: "phone" },
                { type: "sim" },
                { type: "smartphone" },
                { type: "energy" },
            ],
            [
                null,
                { type: "sim" },
                { type: "phone" },
                { type: "smartphone" },
                null,
            ],
            [
                null,
                { type: "phone" },
                { type: "smartphone" },
                { type: "energy" },
                null,
            ],
            [
                {
                    type: "discoball",
                    isHelper: true,
                    helperType: "discoball",
                },
                { type: "sim" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "discoball", isHelper: true, helperType: "discoball" },
            ],
        ],
    },

    {
        id: 9,
        name: "Уровень 9",
        rows: 6,
        cols: 6,
        moves: 19,
        difficult: "easy",
        elements: ["smartphone", "sim", "phone", "message"],
        goals: [
            { type: "smartphone", count: 15 },
            { type: "phone", count: 15 },
        ],
        grid: [
            [
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "smartphone" },
                { type: "phone" },
                { type: "smartphone" },
            ],
            [
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                {
                    type: "ice",
                    content: {
                        type: "verticalHelper",
                        isHelper: true,
                        helperType: "verticalHelper",
                    },
                    strength: 2,
                },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "message" },
                { type: "smartphone" },
                { type: "phone" },
            ],
            [
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "sim" },
                { type: "message" },
                { type: "message" },
            ],
            [
                { type: "message" },
                { type: "message" },
                { type: "sim" },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
            ],
            [
                { type: "phone" },
                { type: "smartphone" },
                { type: "message" },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                {
                    type: "ice",
                    content: {
                        type: "horizontalHelper",
                        isHelper: true,
                        helperType: "horizontalHelper",
                    },
                    strength: 2,
                },
                { type: "ice", content: { type: "phone" }, strength: 2 },
            ],
            [
                { type: "smartphone" },
                { type: "phone" },
                { type: "smartphone" },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
            ],
        ],
        isCompleted: false,
    },

    {
        id: 10,
        name: "Уровень 10",
        rows: 6,
        cols: 7,
        moves: 12,
        difficult: "easy",
        elements: ["smartphone", "energy", "sim", "message"],
        goals: [{ type: "smartphone", count: 20 }],
        grid: [
            [
                null,
                { type: "smartphone" },
                { type: "message" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "smartphone" },
                null,
            ],
            [
                null,
                { type: "sim" },
                { type: "sim" },
                { type: "message" },
                { type: "sim" },
                { type: "message" },
                null,
            ],
            [
                null,
                { type: "smartphone" },
                { type: "smartphone" },
                {
                    type: "ice",
                    content: {
                        type: "horizontalHelper",
                        isHelper: true,
                        helperType: "horizontalHelper",
                    },
                    strength: 2,
                },
                { type: "smartphone" },
                { type: "sim" },
                null,
            ],
            [
                { type: "smartphone" },
                { type: "message" },
                { type: "sim" },
                { type: "box", strength: 2 },
                { type: "message" },
                { type: "smartphone" },
                { type: "smartphone" },
            ],
            [
                null,
                { type: "energy" },
                { type: "energy" },
                {
                    type: "ice",
                    content: {
                        type: "horizontalHelper",
                        isHelper: true,
                        helperType: "horizontalHelper",
                    },
                    strength: 2,
                },
                { type: "energy" },
                { type: "energy" },
                null,
            ],
            [
                null,
                null,
                { type: "smartphone" },
                { type: "box", strength: 2 },
                { type: "smartphone" },
                null,
                null,
            ],
        ],
        isCompleted: false,
    },

    {
        id: 11,
        name: "Уровень 11",
        rows: 6,
        cols: 6,
        isCompleted: false,
        moves: 21,
        difficult: "medium",
        elements: ["smartphone", "energy", "sim", "message", "phone"],
        goals: [
            { type: "energy", count: 15 },
            { type: "smartphone", count: 15 },
        ],
        grid: [
            [
                null,
                { type: "smartphone" },
                { type: "phone" },
                { type: "sim" },
                { type: "phone" },
                null,
            ],
            [
                { type: "energy" },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "message" },
                { type: "ice", content: { type: "message" }, strength: 2 },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "ice", content: { type: "energy" }, strength: 2 },
            ],
            [
                { type: "ice", content: { type: "energy" }, strength: 2 },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "energy" },
                { type: "ice", content: { type: "message" }, strength: 2 },
                { type: "smartphone" },
            ],
            [
                { type: "smartphone" },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "smartphone" },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "ice", content: { type: "energy" }, strength: 2 },
            ],
            [
                { type: "phone" },
                { type: "message" },
                { type: "sim" },
                { type: "message" },
                { type: "phone" },
                { type: "sim" },
            ],
            [null, null, { type: "phone" }, { type: "message" }, null, null],
        ],
    },

    {
        id: 12,
        name: "Уровень 12",
        rows: 7,
        cols: 6,
        moves: 3,
        difficult: "hard",
        elements: ["energy", "message", "smartphone", "sim"],
        goals: [{ type: "box_full", count: 2 }],
        grid: [
            // Стандартная 6x6 сетка
            [
                null,
                {
                    type: "box",
                    strength: 2,
                },
                { type: "energy" },
                { type: "sim" },
                { type: "box", strength: 2 },
                null,
            ],
            [
                { type: "smartphone" },
                { type: "energy" },
                { type: "message" },
                { type: "smartphone" },
                { type: "message" },
                { type: "smartphone" },
            ],
            [
                { type: "message" },
                { type: "energy" },
                { type: "energy" },
                { type: "message" },
                { type: "message" },
                { type: "energy" },
            ],
            [
                { type: "energy" },
                { type: "message" },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "energy" },
                { type: "smartphone" },
                { type: "message" },
            ],
            [
                { type: "sim" },
                { type: "smartphone" },
                { type: "energy" },
                {
                    type: "verticalHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                { type: "sim" },
                { type: "energy" },
            ],
            [
                { type: "smartphone" },
                { type: "message" },
                { type: "energy" },
                { type: "message" },
                { type: "smartphone" },
                { type: "sim" },
            ],
            [
                null,
                { type: "smartphone" },
                { type: "sim" },
                { type: "smartphone" },
                { type: "sim" },
                null,
            ],
        ],
        isCompleted: false,
    },

    {
        id: 13,
        name: "Уровень 13",
        rows: 7,
        cols: 7,
        moves: 13,
        difficult: "easy",
        elements: ["phone", "energy", "smartphone", "message"],
        goals: [
            { type: "energy", count: 25 },
            { type: "smartphone", count: 25 },
            { type: "box_full", count: 15 },
        ],
        grid: [
            // Стандартная 6x6 сетка
            [
                { type: "phone" },
                {
                    type: "phone",
                },
                { type: "message" },
                { type: "phone" },
                { type: "message" },
                { type: "phone" },
                { type: "phone" },
            ],
            [
                { type: "box", strength: 2 },
                { type: "phone" },
                { type: "energy" },
                { type: "discoball", isHelper: true, helperType: "discoball" },
                { type: "smartphone" },
                { type: "phone" },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                // {
                //     type: "horizontalHelper",
                //     isHelper: true,
                //     helperType: "horizontalHelper",
                // },
                {
                    type: "ice",
                    content: {
                        type: "horizontalHelper",
                        isHelper: true,
                        helperType: "horizontalHelper",
                    },
                    strength: 2,
                },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "energy" },
                { type: "smartphone" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "energy" },
            ],
            [
                { type: "smartphone" },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "smartphone" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "smartphone" },
            ],
            [
                { type: "energy" },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "energy" },
                { type: "smartphone" },
                { type: "energy" },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "energy" },
            ],
        ],
        isCompleted: false,
    },

    {
        id: 14,
        name: "Уровень 14",
        rows: 7,
        cols: 7,
        isCompleted: false,
        moves: 11,
        difficult: "hard",
        elements: ["smartphone", "phone", "sim", "message"],
        goals: [{ type: "box_full", count: 17 }],
        grid: [
            [
                { type: "message" },
                { type: "message" },
                { type: "phone" },
                { type: "message" },
                { type: "phone" },
                { type: "smartphone" },
                { type: "sim" },
            ],
            [
                { type: "phone" },
                { type: "smartphone" },
                { type: "sim" },
                { type: "smartphone" },
                { type: "sim" },
                { type: "phone" },
                { type: "message" },
            ],
            [
                { type: "smartphone" },
                { type: "message" },
                { type: "message" },
                { type: "sim" },
                { type: "message" },
                { type: "message" },
                { type: "phone" },
            ],
            [
                { type: "message" },
                { type: "sim" },
                { type: "sim" },
                { type: "message" },
                { type: "sim" },
                { type: "sim" },
                { type: "message" },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "message" },
                { type: "sim" },
                { type: "message" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "message" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
        ],
    },

    {
        id: 15,
        name: "Уровень 15",
        rows: 7,
        cols: 5,
        isCompleted: false,
        moves: 11,
        difficult: "medium",
        elements: ["smartphone", "energy", "sim", "message", "phone"],
        goals: [{ type: "box_full", count: 11 }],
        grid: [
            [
                { type: "message" },
                { type: "message" },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "phone" },
                { type: "energy" },
            ],
            [
                { type: "phone" },
                { type: "sim" },
                { type: "sim" },
                { type: "message" },
                { type: "phone" },
            ],
            [
                { type: "message" },
                { type: "energy" },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "phone" },
                { type: "energy" },
            ],
            [
                { type: "message" },
                { type: "phone" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "phone" },
            ],
            [
                { type: "box", strength: 2 },
                { type: "sim" },
                { type: "sim" },
                { type: "energy" },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "energy" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
        ],
    },

    {
        id: 16,
        name: "Уровень 16",
        rows: 6,
        cols: 5,
        moves: 15,
        difficult: "easy",
        elements: ["smartphone", "sim", "message"],
        goals: [
            { type: "message", count: 25 },
            { type: "sim", count: 25 },
        ],
        grid: [
            [
                null,
                { type: "sim" },
                {
                    type: "verticalHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                { type: "sim" },
                null,
            ],
            [
                null,
                { type: "message" },
                { type: "sim" },
                { type: "message" },
                null,
            ],
            [
                {
                    type: "verticalHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                { type: "sim" },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "sim" },
                {
                    type: "verticalHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
            ],
            [
                { type: "sim" },
                { type: "message" },
                { type: "sim" },
                { type: "message" },
                { type: "sim" },
            ],
            [
                { type: "message" },
                { type: "sim" },
                { type: "message" },
                { type: "sim" },
                { type: "message" },
            ],
            [
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                {
                    type: "verticalHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                { type: "sim" },
                {
                    type: "verticalHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
            ],
        ],
        isCompleted: false,
    },

    {
        id: 17,
        name: "Уровень 17",
        rows: 7,
        cols: 6,
        isCompleted: false,
        moves: 17,
        difficult: "hard",
        elements: ["smartphone", "energy", "sim", "message", "phone"],
        goals: [
            { type: "smartphone", count: 20 },
            { type: "energy", count: 20 },
        ],
        grid: [
            [
                null,
                { type: "smartphone" },
                {
                    type: "verticalHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                {
                    type: "verticalHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                { type: "energy" },
                null,
            ],
            [
                { type: "box", strength: 2 },
                { type: "energy" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "smartphone" },
                { type: "box", strength: 2 },
            ],
            [
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "smartphone" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "phone" },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
            ],
            [
                { type: "box", strength: 2 },
                { type: "energy" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "smartphone" },
                { type: "box", strength: 2 },
            ],
            [
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "smartphone" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "energy" },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
            ],
            [
                { type: "box", strength: 2 },
                { type: "phone" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "message" },
                { type: "box", strength: 2 },
            ],
            [
                null,
                {
                    type: "verticalHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                { type: "smartphone" },
                { type: "energy" },
                {
                    type: "verticalHelper",
                    isHelper: true,
                    helperType: "verticalHelper",
                },
                null,
            ],
        ],
    },

    {
        id: 18,
        name: "Уровень 18",
        rows: 7,
        cols: 6,
        isCompleted: false,
        moves: 16,
        difficult: "medium",
        elements: ["smartphone", "energy", "sim", "message", "phone"],
        goals: [
            { type: "message", count: 15 },
            { type: "sim", count: 15 },
            { type: "box_full", count: 4 },
        ],
        grid: [
            [
                { type: "energy" },
                { type: "message" },
                { type: "smartphone" },
                { type: "smartphone" },
                { type: "energy" },
                { type: "smartphone" },
            ],
            [
                { type: "message" },
                { type: "phone" },
                { type: "message" },
                { type: "phone" },
                { type: "smartphone" },
                { type: "phone" },
            ],
            [
                null,
                { type: "box", strength: 2 },
                { type: "phone" },
                { type: "sim" },
                { type: "box", strength: 2 },
                null,
            ],
            [
                { type: "box", strength: 2 },
                { type: "phone" },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "sim" }, strength: 2 },
                { type: "smartphone" },
                { type: "box", strength: 2 },
            ],

            [
                { type: "smartphone" },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "sim" },
                { type: "energy" },
                { type: "ice", content: { type: "sim" }, strength: 2 },
                { type: "sim" },
            ],
            [
                { type: "phone" },
                null,
                { type: "smartphone" },
                { type: "sim" },
                null,
                { type: "phone" },
            ],
            [
                { type: "energy" },
                { type: "energy" },
                { type: "message" },
                { type: "energy" },
                { type: "message" },
                { type: "message" },
            ],
        ],
    },

    {
        id: 19,
        name: "Уровень 19",
        rows: 7,
        cols: 7,
        isCompleted: false,
        moves: 19,
        difficult: "hard",
        elements: ["smartphone", "energy", "phone", "message"],
        goals: [{ type: "box_full", count: 20 }],
        grid: [
            [
                { type: "box", strength: 2 },
                { type: "smartphone" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "smartphone" },
                { type: "phone" },
                { type: "smartphone" },
            ],
            [
                { type: "box", strength: 2 },
                { type: "energy" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "smartphone" },
                { type: "box", strength: 2 },
            ],
            [
                { type: "energy" },
                { type: "message" },
                { type: "energy" },
                {
                    type: "ice",
                    content: {
                        type: "horizontalHelper",
                        isHelper: true,
                        helperType: "horizontalHelper",
                    },
                    strength: 2,
                },
                { type: "message" },
                { type: "smartphone" },
                { type: "box", strength: 2 },
            ],
            [
                { type: "message" },
                { type: "energy" },
                { type: "phone" },
                { type: "energy" },
                { type: "phone" },
                { type: "energy" },
                { type: "smartphone" },
            ],
            [
                { type: "box", strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "ice", content: { type: "message" }, strength: 2 },
                { type: "ice", content: { type: "message" }, strength: 2 },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
        ],
    },

    {
        id: 20,
        name: "Уровень 20",
        rows: 5,
        cols: 5,
        isCompleted: false,
        moves: 9,
        difficult: "easy",
        elements: ["smartphone", "energy", "message"],
        goals: [
            { type: "box_full", count: 6 },
            { type: "smartphone", count: 20 },
        ],
        grid: [
            [
                null,
                { type: "box", strength: 2 },
                { type: "smartphone" },
                { type: "box", strength: 2 },
                null,
            ],
            [
                null,
                { type: "smartphone" },
                { type: "energy" },
                { type: "smartphone" },
                null,
            ],
            [
                { type: "smartphone" },
                { type: "box", strength: 2 },
                { type: "smartphone" },
                { type: "box", strength: 2 },
                { type: "energy" },
            ],
            [
                { type: "smartphone" },
                { type: "box", strength: 2 },
                { type: "smartphone" },
                { type: "box", strength: 2 },
                { type: "energy" },
            ],
            [
                { type: "energy" },
                { type: "smartphone" },
                null,
                { type: "energy" },
                { type: "smartphone" },
            ],
        ],
    },

    {
        id: 21,
        name: "Уровень 21",
        rows: 5,
        cols: 5,
        isCompleted: false,
        moves: 6,
        difficult: "easy",
        elements: ["sim", "energy", "phone", "message"],
        goals: [
            { type: "phone", count: 10 },
            { type: "energy", count: 10 },
        ],
        grid: [
            [
                { type: "phone" },
                { type: "energy" },
                null,
                { type: "phone" },
                { type: "energy" },
            ],
            [
                { type: "phone" },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "energy" },
            ],
            [
                { type: "energy" },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                {
                    type: "horizontalHelper",
                    isHelper: true,
                    helperType: "horizontalHelper",
                },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "phone" },
            ],
            [
                { type: "phone" },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "ice", content: { type: "phone" }, strength: 2 },
                { type: "energy" },
            ],
            [
                { type: "phone" },
                { type: "energy" },
                null,
                { type: "phone" },
                { type: "energy" },
            ],
        ],
    },

    {
        id: 22,
        name: "Уровень 22",
        rows: 5,
        cols: 5,
        isCompleted: false,
        moves: 10,
        difficult: "medium",
        elements: ["smartphone", "energy", "phone", "message"],
        goals: [{ type: "phone", count: 15 }],
        grid: [
            [
                { type: "phone" },
                { type: "message" },
                { type: "smartphone" },
                { type: "phone" },
                null,
            ],
            [
                { type: "message" },
                { type: "phone" },
                { type: "smartphone" },
                { type: "message" },
                { type: "phone" },
            ],
            [
                { type: "phone" },
                { type: "smartphone" },
                { type: "phone" },
                { type: "smartphone" },
                { type: "phone" },
            ],
            [
                { type: "phone" },
                { type: "message" },
                { type: "smartphone" },
                { type: "phone" },
                { type: "message" },
            ],
            [
                null,
                { type: "phone" },
                { type: "smartphone" },
                { type: "message" },
                { type: "phone" },
            ],
        ],
    },

    {
        id: 23,
        name: "Уровень 23",
        rows: 7,
        cols: 6,
        isCompleted: false,
        moves: 20,
        difficult: "easy",
        elements: ["smartphone", "energy", "sim"],
        goals: [
            { type: "energy", count: 20 },
            { type: "smartphone", count: 20 },
            { type: "box_full", count: 21 },
        ],
        grid: [
            [null, { type: "sim" }, { type: "sim" }, null, null, null],
            [
                { type: "smartphone" },
                { type: "smartphone" },
                { type: "energy" },
                { type: "smartphone" },
                null,
                null,
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "smartphone" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "energy" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "energy" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                null,
                null,
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                null,
                null,
                null,
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                null,
            ],
        ],
    },

    {
        id: 24,
        name: "Уровень 24",
        rows: 6,
        cols: 5,
        isCompleted: false,
        moves: 10,
        difficult: "medium",
        elements: ["smartphone", "energy", "sim", "message"],
        goals: [{ type: "box_full", count: 9 }],
        grid: [
            [
                { type: "message" },
                { type: "message" },
                { type: "sim" },
                { type: "energy" },
                { type: "message" },
            ],
            [
                { type: "smartphone" },
                { type: "sim" },
                { type: "smartphone" },
                { type: "smartphone" },
                { type: "energy" },
            ],
            [
                { type: "energy" },
                { type: "energy" },
                { type: "sim" },
                { type: "energy" },
                { type: "smartphone" },
            ],
            [
                { type: "box", strength: 2 },
                { type: "smartphone" },
                { type: "message" },
                { type: "energy" },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "message" },
                { type: "sim" },
                { type: "message" },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
            ],
        ],
    },

    {
        id: 25,
        name: "Уровень 25",
        rows: 7,
        cols: 6,
        isCompleted: false,
        moves: 10,
        difficult: "easy",
        elements: ["smartphone", "energy", "phone", "message"],
        goals: [
            { type: "energy", count: 12 },
            { type: "box_full", count: 6 },
        ],
        grid: [
            [null, null, { type: "message" }, { type: "energy" }, null, null],
            [
                null,
                { type: "message" },
                { type: "energy" },
                { type: "message" },
                { type: "energy" },
                null,
            ],
            [
                null,
                { type: "phone" },
                { type: "message" },
                { type: "smartphone" },
                { type: "smartphone" },
                null,
            ],

            [
                { type: "box", strength: 2 },
                { type: "energy" },
                { type: "message" },
                { type: "phone" },
                { type: "smartphone" },
                { type: "box", strength: 2 },
            ],
            [
                { type: "box", strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "ice", content: { type: "smartphone" }, strength: 2 },
                { type: "ice", content: { type: "energy" }, strength: 2 },
                { type: "box", strength: 2 },
            ],
            [
                { type: "energy" },
                { type: "energy" },
                { type: "phone" },
                { type: "energy" },
                { type: "smartphone" },
                { type: "phone" },
            ],
            [
                null,
                { type: "message" },
                { type: "box", strength: 2 },
                { type: "box", strength: 2 },
                { type: "phone" },
                null,
            ],
        ],
    },
];
